#!/usr/bin/env bash
#
# vim: set ft=sh:
#
# @description Generates sparklines for a set of data
# @import spark/spark

help()
{
    local spark
    spark="$(basename "${BASH_SOURCE[0]}")"

    cat <<EOF

  USAGE:
  $spark [-h|--help] VALUE,...

  EXAMPLES:
  $spark 1 5 22 13 53
  ▁▁▃▂█
  $spark 0,30,55,80,33,150
  ▁▂▃▄▂█
  echo 9 13 5 17 1 | $spark
  ▄▆▂█▁

EOF
}

main ()
{
    verbose true
    strict true

    # show help for no arguments if stdin is a terminal
    if { [ -z "$1" ] && [ -t 0 ] ; } || [ "$1" == '-h' ] || [ "$1" == '--help' ]
    then
        help
        exit 0
    fi

    _ spark "${@:-$(cat)}"
}
